use chrono::{DateTime, Duration, TimeZone, Utc};
use smc_nlq::parse_query_with_ref_time;

fn fixed_now() -> DateTime<Utc> {
    Utc.with_ymd_and_hms(2026, 9, 22, 14, 30, 0).unwrap()
}

struct TestCase {
    name: &'static str,
    query: &'static str,
    expected_text: &'static str,
    expected_file_types: &'static [&'static str],
    check_after: Option<DateTime<Utc>>,
    check_before: Option<DateTime<Utc>>,
    expected_location: &'static [&'static str],
    is_project: bool,
    is_screenshot: bool,
}

#[test]
fn test_comprehensive_nlq_table() {
    let now = fixed_now();

    let tests = vec![
        // --- 1. Basic & Plain Queries ---
        TestCase {
            name: "plain search text",
            query: "quarterly financial results",
            expected_text: "quarterly financial results",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "single keyword",
            query: "dockerfile",
            expected_text: "dockerfile",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "empty string",
            query: "",
            expected_text: "",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "spaces only",
            query: "   ",
            expected_text: "",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        // --- 2. File Type Parsing ---
        TestCase {
            name: "pdf query",
            query: "marketing budget pdf",
            expected_text: "marketing budget",
            expected_file_types: &["pdf"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "word doc query",
            query: "employment contract word document",
            expected_text: "employment contract",
            expected_file_types: &["docx", "doc", "rtf", "odt"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "docx short keyword",
            query: "meeting notes docx",
            expected_text: "meeting",
            expected_file_types: &["docx", "doc", "rtf", "odt"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "excel spreadsheet query",
            query: "q3 expenses excel spreadsheet",
            expected_text: "q3 expenses",
            expected_file_types: &["xlsx", "xls", "csv", "ods"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "csv sheet query",
            query: "users export csv",
            expected_text: "users export",
            expected_file_types: &["xlsx", "xls", "csv", "ods"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "powerpoint slides query",
            query: "investor pitch deck presentation slides",
            expected_text: "investor pitch deck",
            expected_file_types: &["pptx", "ppt", "odp"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "pptx short form",
            query: "product roadmap pptx",
            expected_text: "product roadmap",
            expected_file_types: &["pptx", "ppt", "odp"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "images and pictures",
            query: "team offsite photo image",
            expected_text: "team offsite",
            expected_file_types: &["png", "jpg", "jpeg", "webp", "svg", "gif"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "code script query",
            query: "deploy pipeline script",
            expected_text: "deploy pipeline",
            expected_file_types: &[
                "rs", "ts", "tsx", "js", "jsx", "py", "go", "c", "cpp", "h", "hpp", "java", "sql",
                "sh", "ps1",
            ],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "rust specific source",
            query: "database migrations in rust",
            expected_text: "database migrations",
            expected_file_types: &["rs"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "python script",
            query: "data processing in python",
            expected_text: "data processing",
            expected_file_types: &["py"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "typescript code",
            query: "frontend components typescript",
            expected_text: "frontend components",
            expected_file_types: &["ts", "tsx"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "golang code",
            query: "microservice auth in golang",
            expected_text: "microservice auth",
            expected_file_types: &["go"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "sql query script",
            query: "analytics schema sql query",
            expected_text: "analytics schema",
            expected_file_types: &["sql"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "markdown notes",
            query: "architecture diagram markdown notes",
            expected_text: "architecture diagram",
            expected_file_types: &["md", "txt", "org"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "zip archive query",
            query: "database backup zip archive",
            expected_text: "database backup",
            expected_file_types: &["zip", "tar", "gz", "7z", "rar"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        // --- 3. Date & Relative Time Expressions (now = 2026-09-22) ---
        TestCase {
            name: "today",
            query: "logs from today",
            expected_text: "logs",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 9, 22, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 9, 22, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "yesterday",
            query: "error report yesterday",
            expected_text: "error report",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 9, 21, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 9, 21, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "this week (2026-09-22 is Tuesday -> Mon is 2026-09-21)",
            query: "invoices this week",
            expected_text: "invoices",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 9, 21, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 9, 22, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "last week (Mon 2026-09-14 to Sun 2026-09-20)",
            query: "sprint planning notes last week",
            expected_text: "sprint planning",
            expected_file_types: &["md", "txt", "org"],
            check_after: Some(Utc.with_ymd_and_hms(2026, 9, 14, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 9, 20, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "this month (September 2026)",
            query: "receipts this month",
            expected_text: "receipts",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 9, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 9, 22, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "last month (August 2026 -> 31 days)",
            query: "contracts from last month",
            expected_text: "contracts",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 8, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 8, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "this year (2026)",
            query: "taxes this year",
            expected_text: "taxes",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 12, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "last year (2025)",
            query: "audits last year",
            expected_text: "audits",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2025, 1, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2025, 12, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "past 3 days",
            query: "system logs past 3 days",
            expected_text: "system logs",
            expected_file_types: &[],
            check_after: Some(now - Duration::days(3)),
            check_before: Some(now),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "last 2 weeks",
            query: "git commits last 2 weeks",
            expected_text: "git commits",
            expected_file_types: &[],
            check_after: Some(now - Duration::days(14)),
            check_before: Some(now),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "past 6 months",
            query: "invoices past 6 months",
            expected_text: "invoices",
            expected_file_types: &[],
            check_after: Some(now - Duration::days(180)),
            check_before: Some(now),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        // --- 4. Month Specific & Year Expressions ---
        TestCase {
            name: "in January (past month in current year)",
            query: "tax return in January",
            expected_text: "tax return",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 1, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "in March 2024",
            query: "quarterly report in March 2024",
            expected_text: "quarterly report",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2024, 3, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2024, 3, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "in 2024",
            query: "security audit in 2024",
            expected_text: "security audit",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2024, 1, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2024, 12, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "after 2025-06-01",
            query: "receipts after 2025-06-01",
            expected_text: "receipts",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2025, 6, 1, 0, 0, 0).unwrap()),
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "before 2025-12-31",
            query: "contracts before 2025-12-31",
            expected_text: "contracts",
            expected_file_types: &[],
            check_after: None,
            check_before: Some(Utc.with_ymd_and_hms(2025, 12, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        // --- 5. Location Hints & Ctime Flags ---
        TestCase {
            name: "downloaded keyword sets ctime and downloads location",
            query: "machine learning paper downloaded last month",
            expected_text: "machine learning paper",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 8, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 8, 31, 23, 59, 59).unwrap()),
            expected_location: &["downloads"],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "on my desktop",
            query: "budget spreadsheet on my desktop",
            expected_text: "budget",
            expected_file_types: &["xlsx", "xls", "csv", "ods"],
            check_after: None,
            check_before: None,
            expected_location: &["desktop"],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "in documents folder",
            query: "patent application in documents",
            expected_text: "patent application",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &["documents"],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "under invoices folder",
            query: "acme corporation under invoices",
            expected_text: "acme corporation",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &["invoices"],
            is_project: false,
            is_screenshot: false,
        },
        // --- 6. Intent Classification & Project Queries ---
        TestCase {
            name: "where is my project",
            query: "where is my NutriGrade project",
            expected_text: "NutriGrade",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: true,
            is_screenshot: false,
        },
        TestCase {
            name: "where is repo",
            query: "where is smc repo",
            expected_text: "smc",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: true,
            is_screenshot: false,
        },
        TestCase {
            name: "rust backend workspace",
            query: "backend workspace",
            expected_text: "backend",
            expected_file_types: &[],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: true,
            is_screenshot: false,
        },
        TestCase {
            name: "screenshots with qr",
            query: "screenshots with a payment QR",
            expected_text: "",
            expected_file_types: &["png", "jpg", "jpeg", "webp"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: true,
        },
        TestCase {
            name: "screen capture error",
            query: "screen capture error dialog on desktop",
            expected_text: "error dialog",
            expected_file_types: &["png", "jpg", "jpeg", "webp"],
            check_after: None,
            check_before: None,
            expected_location: &["desktop"],
            is_project: false,
            is_screenshot: true,
        },
        // --- 7. Conversational Filler Word Stripping ---
        TestCase {
            name: "find that pdf about AI agents",
            query: "find that pdf about AI agents I downloaded last month",
            expected_text: "AI agents",
            expected_file_types: &["pdf"],
            check_after: Some(Utc.with_ymd_and_hms(2026, 8, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 8, 31, 23, 59, 59).unwrap()),
            expected_location: &["downloads"],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "show me all presentations",
            query: "show me all presentations about quarterly revenue",
            expected_text: "quarterly revenue",
            expected_file_types: &["pptx", "ppt", "odp"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "look for the word document with contracts",
            query: "look for the word document with vendor contracts",
            expected_text: "vendor contracts",
            expected_file_types: &["docx", "doc", "rtf", "odt"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "search for python code files",
            query: "search for python code files about neural networks",
            expected_text: "neural networks",
            expected_file_types: &["py"],
            check_after: None,
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "get me the spreadsheet",
            query: "get me the spreadsheet for 2026 budget",
            expected_text: "budget",
            expected_file_types: &["xlsx", "xls", "csv", "ods"],
            check_after: Some(Utc.with_ymd_and_hms(2026, 1, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 12, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        // --- 8. Edge Cases & Boundary Conditions ---
        TestCase {
            name: "ambiguous word may",
            query: "in May financial plan",
            expected_text: "financial plan",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2026, 5, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2026, 5, 31, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "leap year february in 2024 (29 days)",
            query: "sales data in February 2024",
            expected_text: "sales data",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2024, 2, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2024, 2, 29, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "non leap year february in 2025 (28 days)",
            query: "tax summary in February 2025",
            expected_text: "tax summary",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2025, 2, 1, 0, 0, 0).unwrap()),
            check_before: Some(Utc.with_ymd_and_hms(2025, 2, 28, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "slash date format MM/DD/YYYY",
            query: "invoices after 03/15/2025",
            expected_text: "invoices",
            expected_file_types: &[],
            check_after: Some(Utc.with_ymd_and_hms(2025, 3, 15, 0, 0, 0).unwrap()),
            check_before: None,
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
        TestCase {
            name: "dash date format YYYY-MM-DD",
            query: "deliverables before 2026-11-30",
            expected_text: "deliverables",
            expected_file_types: &[],
            check_after: None,
            check_before: Some(Utc.with_ymd_and_hms(2026, 11, 30, 23, 59, 59).unwrap()),
            expected_location: &[],
            is_project: false,
            is_screenshot: false,
        },
    ];

    let mut total_passed = 0;
    for tc in &tests {
        let parsed = parse_query_with_ref_time(tc.query, now);

        assert_eq!(
            parsed.text, tc.expected_text,
            "Failed text match for test case '{}' (query: '{}')",
            tc.name, tc.query
        );

        for expected_ext in tc.expected_file_types {
            assert!(
                parsed.file_types.contains(&expected_ext.to_string()),
                "Missing file type '{}' for test case '{}' (got: {:?})",
                expected_ext,
                tc.name,
                parsed.file_types
            );
        }

        if let Some(expected_after) = tc.check_after {
            assert_eq!(
                parsed.after,
                Some(expected_after),
                "Mismatch in 'after' timestamp for test case '{}'",
                tc.name
            );
        }

        if let Some(expected_before) = tc.check_before {
            assert_eq!(
                parsed.before,
                Some(expected_before),
                "Mismatch in 'before' timestamp for test case '{}'",
                tc.name
            );
        }

        for loc in tc.expected_location {
            assert!(
                parsed.location_hints.contains(&loc.to_string()),
                "Missing location hint '{}' for test case '{}' (got: {:?})",
                loc,
                tc.name,
                parsed.location_hints
            );
        }

        assert_eq!(
            parsed.is_project_query, tc.is_project,
            "Mismatch in is_project for test case '{}'",
            tc.name
        );

        assert_eq!(
            parsed.is_screenshot_query, tc.is_screenshot,
            "Mismatch in is_screenshot for test case '{}'",
            tc.name
        );

        total_passed += 1;
    }

    println!("All {} table-driven NLQ parser tests PASSED!", total_passed);
}

#[test]
fn test_additional_nlq_phrases_suite() {
    let now = fixed_now();

    // 45 additional distinct query phrase variations (Total > 80 test cases)
    let additional_queries = vec![
        (
            "find pdf in downloads",
            vec!["pdf"],
            vec!["downloads"],
            false,
        ),
        ("where is my website repo", vec![], vec![], true),
        (
            "show me spreadsheets from yesterday",
            vec!["xlsx"],
            vec![],
            false,
        ),
        (
            "get all images on desktop",
            vec!["png"],
            vec!["desktop"],
            false,
        ),
        ("search for rust source code", vec!["rs"], vec![], false),
        (
            "python script in machine_learning folder",
            vec!["py"],
            vec!["machine_learning"],
            false,
        ),
        ("contracts from 2024", vec![], vec![], false),
        ("slides from this week", vec!["pptx"], vec![], false),
        ("word documents past 2 weeks", vec!["docx"], vec![], false),
        ("screenshots from today", vec!["png"], vec![], false),
        (
            "where is my search-my-computer project",
            vec![],
            vec![],
            true,
        ),
        (
            "zip archives in downloads",
            vec!["zip"],
            vec!["downloads"],
            false,
        ),
        ("markdown notes about meeting", vec!["md"], vec![], false),
        (
            "typescript components in frontend",
            vec!["ts"],
            vec!["frontend"],
            false,
        ),
        ("sql queries under db", vec!["sql"], vec!["db"], false),
        (
            "csv data downloaded yesterday",
            vec!["xlsx"],
            vec!["downloads"],
            false,
        ),
        (
            "go source files in backend",
            vec!["go"],
            vec!["backend"],
            false,
        ),
        ("invoices from January 2025", vec![], vec![], false),
        ("tax return in February 2026", vec![], vec![], false),
        ("legal agreement pdf last year", vec!["pdf"], vec![], false),
        ("employee handbook docx", vec!["docx"], vec![], false),
        ("financial model excel sheet", vec!["xlsx"], vec![], false),
        (
            "board meeting presentation ppt",
            vec!["pptx"],
            vec![],
            false,
        ),
        ("system architecture note", vec!["md"], vec![], false),
        ("backup tar archive", vec!["zip"], vec![], false),
        (
            "photo of whiteboard on desktop",
            vec!["png"],
            vec!["desktop"],
            false,
        ),
        ("find c++ header files", vec!["cpp"], vec![], false),
        ("where is the api repository", vec![], vec![], true),
        ("look for rust code past 5 days", vec!["rs"], vec![], false),
        (
            "get pdf files before 2025-01-01",
            vec!["pdf"],
            vec![],
            false,
        ),
        (
            "show python notebooks under research",
            vec!["py"],
            vec!["research"],
            false,
        ),
        ("excel sheets after 2026-01-01", vec!["xlsx"], vec![], false),
        ("user survey csv export", vec!["xlsx"], vec![], false),
        (
            "company overview slides in marketing",
            vec!["pptx"],
            vec!["marketing"],
            false,
        ),
        ("screen capture of bug dialog", vec!["png"], vec![], false),
        ("where is my deep learning project", vec![], vec![], true),
        ("notes from past 10 days", vec!["md"], vec![], false),
        ("word doc under legal", vec!["docx"], vec!["legal"], false),
        ("rust cli workspace", vec![], vec![], true),
        (
            "pdf invoice downloaded last week",
            vec!["pdf"],
            vec!["downloads"],
            false,
        ),
        ("photos from last month", vec!["png"], vec![], false),
        ("sql migration scripts", vec!["sql"], vec![], false),
        (
            "golang server under services",
            vec!["go"],
            vec!["services"],
            false,
        ),
        (
            "typescript types in shared folder",
            vec!["ts"],
            vec!["shared"],
            false,
        ),
        (
            "archive files on desktop",
            vec!["zip"],
            vec!["desktop"],
            false,
        ),
    ];

    for (query, expected_types, expected_loc, is_proj) in additional_queries {
        let parsed = parse_query_with_ref_time(query, now);
        if !expected_types.is_empty() {
            assert!(
                !parsed.file_types.is_empty(),
                "Expected file types for query '{}'",
                query
            );
        }
        if !expected_loc.is_empty() {
            assert!(
                !parsed.location_hints.is_empty(),
                "Expected location hints for query '{}'",
                query
            );
        }
        if is_proj {
            assert!(
                parsed.is_project_query,
                "Expected is_project_query to be true for '{}'",
                query
            );
        }
    }
}
